const cnationWordDB = {
kindergarten: [
{ko:"개", en:"dog"}, {ko:"고양이", en:"cat"}, {ko:"사과", en:"apple"}, {ko:"바나나", en:"banana"}, {ko:"포도", en:"grape"}, {ko:"딸기", en:"strawberry"}, {ko:"오렌지", en:"orange"}, {ko:"물", en:"water"}, {ko:"우유", en:"milk"}, {ko:"빵", en:"bread"},
{ko:"엄마", en:"mom"}, {ko:"아빠", en:"dad"}, {ko:"아기", en:"baby"}, {ko:"집", en:"house"}, {ko:"차", en:"car"}, {ko:"버스", en:"bus"}, {ko:"기차", en:"train"}, {ko:"해", en:"sun"}, {ko:"달", en:"moon"}, {ko:"별", en:"star"},
{ko:"눈", en:"eye"}, {ko:"코", en:"nose"}, {ko:"입", en:"mouth"}, {ko:"귀", en:"ear"}, {ko:"손", en:"hand"}, {ko:"발", en:"foot"}, {ko:"머리", en:"head"}, {ko:"팔", en:"arm"}, {ko:"다리", en:"leg"}, {ko:"배", en:"stomach"},
{ko:"빨강", en:"red"}, {ko:"파랑", en:"blue"}, {ko:"노랑", en:"yellow"}, {ko:"초록", en:"green"}, {ko:"검정", en:"black"}, {ko:"하양", en:"white"}, {ko:"분홍", en:"pink"}, {ko:"보라", en:"purple"}, {ko:"주황", en:"orange"}, {ko:"갈색", en:"brown"},
{ko:"하나", en:"one"}, {ko:"둘", en:"two"}, {ko:"셋", en:"three"}, {ko:"넷", en:"four"}, {ko:"다섯", en:"five"}, {ko:"여섯", en:"six"}, {ko:"일곱", en:"seven"}, {ko:"여덟", en:"eight"}, {ko:"아홉", en:"nine"}, {ko:"열", en:"ten"},
{ko:"안녕", en:"hello"}, {ko:"곰", en:"bear"}, {ko:"돼지", en:"pig"}, {ko:"소", en:"cow"}, {ko:"새", en:"bird"}, {ko:"물고기", en:"fish"}, {ko:"쥐", en:"mouse"}, {ko:"오리", en:"duck"}, {ko:"원숭이", en:"monkey"}, {ko:"사자", en:"lion"},
{ko:"호랑이", en:"tiger"}, {ko:"코끼리", en:"elephant"}, {ko:"나무", en:"tree"}, {ko:"꽃", en:"flower"}, {ko:"풀", en:"grass"}, {ko:"하늘", en:"sky"}, {ko:"구름", en:"cloud"}, {ko:"비", en:"rain"}, {ko:"눈(날씨)", en:"snow"}, {ko:"바람", en:"wind"},
{ko:"셔츠", en:"shirt"}, {ko:"바지", en:"pants"}, {ko:"신발", en:"shoes"}, {ko:"모자", en:"hat"}, {ko:"양말", en:"socks"}, {ko:"가방", en:"bag"}, {ko:"책", en:"book"}, {ko:"연필", en:"pencil"}, {ko:"책상", en:"desk"}, {ko:"의자", en:"chair"},
{ko:"문", en:"door"}, {ko:"창문", en:"window"}, {ko:"방", en:"room"}, {ko:"침대", en:"bed"}, {ko:"시계", en:"clock"}, {ko:"장난감", en:"toy"}, {ko:"공", en:"ball"}, {ko:"인형", en:"doll"}, {ko:"로봇", en:"robot"}, {ko:"자전거", en:"bike"},
{ko:"뛰다", en:"run"}, {ko:"걷다", en:"walk"}, {ko:"먹다", en:"eat"}, {ko:"마시다", en:"drink"}, {ko:"자다", en:"sleep"}, {ko:"앉다", en:"sit"}, {ko:"서다", en:"stand"}, {ko:"웃다", en:"laugh"}, {ko:"울다", en:"cry"}, {ko:"놀다", en:"play"}
],
elementary: [
{ko:"학교", en:"school"}, {ko:"선생님", en:"teacher"}, {ko:"학생", en:"student"}, {ko:"교실", en:"classroom"}, {ko:"숙제", en:"homework"}, {ko:"공부", en:"study"}, {ko:"친구", en:"friend"}, {ko:"가족", en:"family"}, {ko:"사람", en:"person"}, {ko:"소년", en:"boy"},
{ko:"소녀", en:"girl"}, {ko:"남자", en:"man"}, {ko:"여자", en:"woman"}, {ko:"의사", en:"doctor"}, {ko:"간호사", en:"nurse"}, {ko:"경찰", en:"police"}, {ko:"소방관", en:"firefighter"}, {ko:"요리사", en:"chef"}, {ko:"농부", en:"farmer"}, {ko:"가수", en:"singer"},
{ko:"음악", en:"music"}, {ko:"미술", en:"art"}, {ko:"수학", en:"math"}, {ko:"과학", en:"science"}, {ko:"역사", en:"history"}, {ko:"아침", en:"morning"}, {ko:"오후", en:"afternoon"}, {ko:"저녁", en:"evening"}, {ko:"밤", en:"night"}, {ko:"오늘", en:"today"},
{ko:"내일", en:"tomorrow"}, {ko:"어제", en:"yesterday"}, {ko:"주", en:"week"}, {ko:"달", en:"month"}, {ko:"년", en:"year"}, {ko:"월요일", en:"monday"}, {ko:"화요일", en:"tuesday"}, {ko:"수요일", en:"wednesday"}, {ko:"목요일", en:"thursday"}, {ko:"금요일", en:"friday"},
{ko:"토요일", en:"saturday"}, {ko:"일요일", en:"sunday"}, {ko:"봄", en:"spring"}, {ko:"여름", en:"summer"}, {ko:"가을", en:"fall"}, {ko:"겨울", en:"winter"}, {ko:"따뜻한", en:"warm"}, {ko:"시원한", en:"cool"}, {ko:"더운", en:"hot"}, {ko:"추운", en:"cold"},
{ko:"빠른", en:"fast"}, {ko:"느린", en:"slow"}, {ko:"큰", en:"big"}, {ko:"작은", en:"small"}, {ko:"긴", en:"long"}, {ko:"짧은", en:"short"}, {ko:"높은", en:"high"}, {ko:"낮은", en:"low"}, {ko:"무거운", en:"heavy"}, {ko:"가벼운", en:"light"},
{ko:"새로운", en:"new"}, {ko:"오래된", en:"old"}, {ko:"좋은", en:"good"}, {ko:"나쁜", en:"bad"}, {ko:"행복한", en:"happy"}, {ko:"슬픈", en:"sad"}, {ko:"화난", en:"angry"}, {ko:"피곤한", en:"tired"}, {ko:"배고픈", en:"hungry"}, {ko:"목마른", en:"thirsty"},
{ko:"병원", en:"hospital"}, {ko:"공원", en:"park"}, {ko:"상점", en:"store"}, {ko:"은행", en:"bank"}, {ko:"식당", en:"restaurant"}, {ko:"도서관", en:"library"}, {ko:"시장", en:"market"}, {ko:"도시", en:"city"}, {ko:"마을", en:"town"}, {ko:"거리", en:"street"},
{ko:"아침식사", en:"breakfast"}, {ko:"점심식사", en:"lunch"}, {ko:"저녁식사", en:"dinner"}, {ko:"간식", en:"snack"}, {ko:"맛있는", en:"delicious"}, {ko:"요리하다", en:"cook"}, {ko:"씻다", en:"wash"}, {ko:"청소하다", en:"clean"}, {ko:"돕다", en:"help"}, {ko:"일하다", en:"work"},
{ko:"시작하다", en:"start"}, {ko:"끝내다", en:"finish"}, {ko:"열다", en:"open"}, {ko:"닫다", en:"close"}, {ko:"밀다", en:"push"}, {ko:"당기다", en:"pull"}, {ko:"던지다", en:"throw"}, {ko:"잡다", en:"catch"}, {ko:"수영하다", en:"swim"}, {ko:"그리다", en:"draw"}
],
middle: [
{ko:"환경", en:"environment"}, {ko:"경험", en:"experience"}, {ko:"발전하다", en:"develop"}, {ko:"향상시키다", en:"improve"}, {ko:"인기있는", en:"popular"}, {ko:"다양한", en:"various"}, {ko:"전통적인", en:"traditional"}, {ko:"제안하다", en:"suggest"}, {ko:"목적", en:"purpose"}, {ko:"결정하다", en:"decide"},
{ko:"분석하다", en:"analyze"}, {ko:"이익", en:"benefit"}, {ko:"도전", en:"challenge"}, {ko:"효과", en:"effect"}, {ko:"요인", en:"factor"}, {ko:"발생시키다", en:"generate"}, {ko:"식별하다", en:"identify"}, {ko:"유지하다", en:"maintain"}, {ko:"발생하다", en:"occur"}, {ko:"수용력", en:"capacity"},
{ko:"근본적인", en:"fundamental"}, {ko:"가설", en:"hypothesis"}, {ko:"암시하다", en:"imply"}, {ko:"수정하다", en:"modify"}, {ko:"객관적인", en:"objective"}, {ko:"관점", en:"perspective"}, {ko:"관련된", en:"relevant"}, {ko:"추상적인", en:"abstract"}, {ko:"포괄적인", en:"comprehensive"}, {ko:"모순", en:"contradiction"},
{ko:"끌어내다", en:"derive"}, {ko:"경험적인", en:"empirical"}, {ko:"변동하다", en:"fluctuate"}, {ko:"계급", en:"hierarchy"}, {ko:"불가피한", en:"inevitable"}, {ko:"패러다임", en:"paradigm"}, {ko:"그다음의", en:"subsequent"}, {ko:"애매한", en:"ambiguous"}, {ko:"인지적인", en:"cognitive"}, {ko:"진퇴양난", en:"dilemma"},
{ko:"명백한", en:"explicit"}, {ko:"본질적인", en:"intrinsic"}, {ko:"은유", en:"metaphor"}, {ko:"실용적인", en:"pragmatic"}, {ko:"회복력있는", en:"resilient"}, {ko:"자발적인", en:"spontaneous"}, {ko:"취약한", en:"vulnerable"}, {ko:"기술", en:"technology"}, {ko:"지식", en:"knowledge"}, {ko:"정보", en:"information"},
{ko:"의사소통", en:"communication"}, {ko:"사회", en:"society"}, {ko:"문화", en:"culture"}, {ko:"경제", en:"economy"}, {ko:"정치", en:"politics"}, {ko:"민주주의", en:"democracy"}, {ko:"독립", en:"independence"}, {ko:"책임", en:"responsibility"}, {ko:"기회", en:"opportunity"}, {ko:"성공", en:"success"},
{ko:"실패", en:"failure"}, {ko:"노력", en:"effort"}, {ko:"인내", en:"patience"}, {ko:"자신감", en:"confidence"}, {ko:"용기", en:"courage"}, {ko:"두려움", en:"fear"}, {ko:"불안", en:"anxiety"}, {ko:"우울증", en:"depression"}, {ko:"스트레스", en:"stress"}, {ko:"건강", en:"health"},
{ko:"질병", en:"disease"}, {ko:"증상", en:"symptom"}, {ko:"치료", en:"treatment"}, {ko:"예방", en:"prevention"}, {ko:"영양", en:"nutrition"}, {ko:"운동", en:"exercise"}, {ko:"근육", en:"muscle"}, {ko:"뼈", en:"bone"}, {ko:"혈액", en:"blood"}, {ko:"심장", en:"heart"},
{ko:"뇌", en:"brain"}, {ko:"폐", en:"lung"}, {ko:"호흡", en:"breathing"}, {ko:"소화", en:"digestion"}, {ko:"신경", en:"nerve"}, {ko:"세포", en:"cell"}, {ko:"유전자", en:"gene"}, {ko:"진화", en:"evolution"}, {ko:"생태계", en:"ecosystem"}, {ko:"오염", en:"pollution"},
{ko:"보존", en:"conservation"}, {ko:"자원", en:"resource"}, {ko:"에너지", en:"energy"}, {ko:"기후", en:"climate"}, {ko:"온도", en:"temperature"}, {ko:"날씨", en:"weather"}, {ko:"재난", en:"disaster"}, {ko:"지진", en:"earthquake"}, {ko:"화산", en:"volcano"}, {ko:"홍수", en:"flood"}
],
high: [
{ko:"일탈", en:"aberration"}, {ko:"변덕스러운", en:"capricious"}, {ko:"단명하는", en:"ephemeral"}, {ko:"까다로운", en:"fastidious"}, {ko:"우상파괴자", en:"iconoclast"}, {ko:"모호하게하다", en:"obfuscate"}, {ko:"현학적인", en:"pedantic"}, {ko:"아첨꾼", en:"sycophant"}, {ko:"어디에나있는", en:"ubiquitous"}, {ko:"열성적인", en:"zealous"},
{ko:"완화하다", en:"alleviate"}, {ko:"합병하다", en:"amalgamate"}, {ko:"모호한", en:"ambiguous"}, {ko:"개선하다", en:"ameliorate"}, {ko:"시대착오", en:"anachronism"}, {ko:"이례적인", en:"anomalous"}, {ko:"반감", en:"antipathy"}, {ko:"무관심", en:"apathy"}, {ko:"달래다", en:"appease"}, {ko:"자의적인", en:"arbitrary"},
{ko:"난해한", en:"arcane"}, {ko:"열정적인", en:"ardor"}, {ko:"기민한", en:"astute"}, {ko:"대담한", en:"audacious"}, {ko:"엄격한", en:"austere"}, {ko:"진부한", en:"banal"}, {ko:"호전적인", en:"bellicose"}, {ko:"자비로운", en:"benign"}, {ko:"지지하다", en:"bolster"}, {ko:"과장", en:"bombast"},
{ko:"촌스러운", en:"boorish"}, {ko:"커지다", en:"burgeon"}, {ko:"소음", en:"cacophony"}, {ko:"솔직한", en:"candid"}, {ko:"흠잡기좋아하는", en:"captious"}, {ko:"비방하다", en:"castigate"}, {ko:"신랄한", en:"caustic"}, {ko:"속임수", en:"chicanery"}, {ko:"응집력있는", en:"cohesive"}, {ko:"설득력있는", en:"compelling"},
{ko:"만족하는", en:"complacent"}, {ko:"타협적인", en:"conciliatory"}, {ko:"용인하다", en:"condone"}, {ko:"혼란시키다", en:"confound"}, {ko:"풍부한", en:"copious"}, {ko:"확증하다", en:"corroborate"}, {ko:"흠잡기쉬운", en:"culpable"}, {ko:"부족", en:"dearth"}, {ko:"존중", en:"deference"}, {ko:"조롱하다", en:"deride"},
{ko:"건조시키다", en:"desiccate"}, {ko:"산만한", en:"desultory"}, {ko:"장광설", en:"diatribe"}, {ko:"몹시부끄러운", en:"diffident"}, {ko:"벗어나다", en:"digress"}, {ko:"애가", en:"dirge"}, {ko:"남을헐뜯다", en:"disparage"}, {ko:"이질적인", en:"disparate"}, {ko:"숨기다", en:"dissemble"}, {ko:"독단적인", en:"dogmatic"},
{ko:"속이다", en:"dupe"}, {ko:"기이한", en:"eccentric"}, {ko:"혼합된", en:"eclectic"}, {ko:"효능", en:"efficacy"}, {ko:"자만심가득한", en:"effrontery"}, {ko:"비가", en:"elegy"}, {ko:"이끌어내다", en:"elicit"}, {ko:"웅변의", en:"eloquent"}, {ko:"미화하다", en:"embellish"}, {ko:"경험적인", en:"empirical"},
{ko:"모방하다", en:"emulate"}, {ko:"약화시키다", en:"enervate"}, {ko:"낳다", en:"engender"}, {ko:"수수께끼", en:"enigma"}, {ko:"일시적인", en:"ephemeral"}, {ko:"평정", en:"equanimity"}, {ko:"모호하게말하다", en:"equivocate"}, {ko:"학식있는", en:"erudite"}, {ko:"난해한", en:"esoteric"}, {ko:"칭송하다", en:"eulogy"},
{ko:"악화시키다", en:"exacerbate"}, {ko:"짜증나게하다", en:"exasperate"}, {ko:"혐오하다", en:"execrate"}, {ko:"무죄를입증하다", en:"exculpate"}, {ko:"긴박성", en:"exigency"}, {ko:"관련없는", en:"extraneous"}, {ko:"화려한", en:"flamboyant"}, {ko:"우연한", en:"fortuitous"}, {ko:"사교적인", en:"gregarious"}, {ko:"속기쉬운", en:"gullible"},
{ko:"이단자", en:"heretic"}, {ko:"방해하다", en:"hinder"}, {ko:"오만", en:"hubris"}, {ko:"우상파괴적인", en:"iconoclastic"}, {ko:"임박한", en:"imminent"}, {ko:"손상시키다", en:"impair"}, {ko:"완고한", en:"implacable"}, {ko:"무모한", en:"impetuous"}, {ko:"불변의", en:"immutable"}, {ko:"방해하다", en:"impede"}
]
};
